### ISSUE TITLE
Schedule: Title layout issue

### ISSUE THREAD

**Issue by clarkefoley** [madglory/level-up#13]
I updated some of the talk titles, and noticed that the longer ones are having a spacing issue.

I wonder if a page break is in order or fixing the wrapping? 

Thanks!!!

![screen shot 2014-09-16 at 5 45 17 pm](https://cloud.githubusercontent.com/assets/427972/4295534/c5eb36aa-3dea-11e4-9fbd-28dc9c98d339.png)

**Comment by blainsmith** [comment]
Ill mess with it tonight!

**Comment by blainsmith** [comment]
The whole schedule time image needs to be redone in order accommodate 2-line titles. For now I will just shorten the titles to be more concise.
