### ISSUE TITLE
Add Mitch Patterson and Kenneth Adams as speakers

### ISSUE THREAD

**Issue by clarkefoley** [madglory/level-up#14]
![mitch-patterson](https://cloud.githubusercontent.com/assets/427972/4482846/42662e98-49ac-11e4-9ca7-6498891acbbd.png)

https://twitter.com/UpstateVC
Co-Founder @hackupstate

![hack-upstate](https://cloud.githubusercontent.com/assets/427972/4482946/0b616128-49ad-11e4-8ab5-f835cc6c5a0e.png)

![kenneth-adams](https://cloud.githubusercontent.com/assets/427972/4482851/44f1341e-49ac-11e4-8e60-843e6434f553.png)

http://esd.ny.gov/AboutUs/Leadership.html

President & NYSED http://esd.ny.gov/index.html
![esd](https://cloud.githubusercontent.com/assets/427972/4482987/445852f2-49ad-11e4-8c4f-e250620ff923.jpg)

**Comment by clarkefoley** [comment]
Added info for each :)

**Comment by bobrown101** [comment]
can I also have the logos that go underneath? por favor

**Comment by clarkefoley** [comment]
added logos!

**Comment by sethlouey** [comment]
@bobrown101 please don't use those logos. I am saving some out for you.
